name: Swift

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install swiftformat
      run: brew install swiftformat

    - name: Install SwiftLint
      run: brew install swiftlint

    - name: Linting
      run: make lint; make check-format

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v --enable-code-coverage

    - name: Upload Code Coverage
      run: make generate-lcov; bash <(curl -s https://codecov.io/bash)
