name: Swift

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install swiftformat/SwiftLint
      run: |
       brew install swiftformat
       brew install swiftlint
    - name: Linting
      run: |
       make lint 
       swiftformat --lint Sources
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-code-coverage  
    - name: Upload Code Coverage 
      run: |
       xcrun llvm-cov export -format="lcov" .build/debug/AEPRulesEnginePackageTests.xctest/Contents/MacOS/AEPRulesEnginePackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov  
       bash <(curl -s https://codecov.io/bash)
     
